fix(08_ordinal_reg): export `transform!`
Closes #83.
Somehow even with `using DataFrames` we are getting:

```shell
UndefVarError: `transform!` not defined
```

Hence, this might fix:

```julia
using DataFrames: transform!
```